### ISSUE TITLE
volk_32f_x2_dot_prod_32f crash on Ettus E310 (ARMv7 Processor rev 0 (v7l))

### ISSUE THREAD

**Issue by ghost** [gnuradio/volk#101]
HI!
I'm working with the board Ettus E310.
The output of cat /proc/cpuinfo is
 $> cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 0 (v7l)
Features        : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpd32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc09
CPU revision    : 0

processor       : 1
model name      : ARMv7 Processor rev 0 (v7l)
Features        : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpd32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc09
CPU revision    : 0

Porting a library on this device that use cmake, I obtain these lines in the file CMakeCache.txt:
// Have function volk_32f_x2_dot_prod_32f
HAVE_VOLK_DOTPROD_F_FUNCTION:INTERNAL=1

in the library there is an #ifdef that test the variable HAVE_VOLK_DOTPROD_F_FUNCTION and if is define call the function volk_32f_x2_dot_prod_32f() and the code crash.

I tried also to download the volk library from the repository recompile and run the make test and the result is 100% passed, but the code crash in any case

**Comment by n-west** [comment]
I think this should be fixed now.
