### ISSUE TITLE
Gnuradio use -DENABLE_STATIC_LIBS=True for volk error

### ISSUE THREAD

**Issue by peterwillcn** [gnuradio/volk#111]
Ubuntu 16.04.2 compile Gnuradio v3.7.10.1 Release
volk/apps/CMakeFiles/volk_profile.dir/build.make:125: recipe for target 'volk/apps/volk_profile' failed
make[2]: *** [volk/apps/volk_profile] Error 1
CMakeFiles/Makefile2:348: recipe for target 'volk/apps/CMakeFiles/volk_profile.dir/all' failed
make[1]: *** [volk/apps/CMakeFiles/volk_profile.dir/all] Error 2
[ 41%] Linking CXX static library libgnuradio-blocks.a
[ 41%] Built target gnuradio-blocks_static
Makefile:160: recipe for target 'all' failed

**Comment by n-west** [comment]
Same issues as your other issue submission in gnuradio #1238. You can't just dump a small snippet of an error with output from a multi-threaded process and expect a fix. These are also probably not bugs as much as they are your environment not working well for some reason.
