### ISSUE TITLE
Feature Request: sin,cos,sincos, log10

### ISSUE THREAD

**Issue by ghostop14** [gnuradio/volk#113]
I just wrapped up a long project to OpenCL enable common gnuradio blocks (gr-clenabled) and did a comprehensive timing study on the native blocks (if you check out the docs folder I published all of the timing results). Based on those results I actually think if there were volk/SSE functions for processing streams in gnuradio for sin,cos,sincos, and log10 that using those in the corresponding blocks like signal generator, quad demod, and log10 could perform twice as fast as the OpenCL versions (which beat the current native code), which may benefit everyone. So I figured I'd submit a feature request to see if it may be possible and how it would perform versus the native code.

Thanks!

**Comment by n-west** [comment]
There are sin, cos, and log10 VOLK kernels. Using them in GNU Radio is up to whoever wants to change those blocks to use the VOLK functions. Any new kernels are pretty much up to individuals to write. You're free to write new kernels and I would merge a sincos kernel, but the impetus for writing new kernels is on individuals that need them.

PS - your opencl stuff is really cool. great work there.
