### ISSUE TITLE
[Website] Issues button link defect

### ISSUE THREAD

**Issue by senden9** [gnuradio/volk#126]
Hi. The big issues button on http://libvolk.org/ just links to `javascript:void(0)`. So effective it links into the  void :wink:.

CSS Path to the button: `html body div.container-fluid div.row div#content.col-sm-9 div.pages.col-sm-12 div.well.page.active div.row.text-center a.btn.btn-primary.btn-large`

**Comment by n-west** [comment]
fixed. thanks
