### ISSUE TITLE
Problem building VOLK with GCC 4.9.2

### ISSUE THREAD

**Issue by dmiralles2009** [gnuradio/volk#138]
Having issues when compiling VOLK with GCC 4.9.2. Initial errors show when doing a for loop initial declaration and it asks for C99 or C11 support. Something similar was discussed in issue #129. However, the solution provided does not seems to solve the issue. As recommended I added  `set(CMAKE_C_FLAGS ${CMAKE_C_FLAGS} c99)` in the top level of the cmakelist.txt  and I got the following error when doing cmake inside the build directory. 
```
CMake Error at lib/CMakeLists.txt:267 (if):
  if given arguments:

    "EQUAL" "64"

  Unknown arguments specified

-- Configuring incomplete, errors occurred!
See also "/root/sdr/src/volk/build/CMakeFiles/CMakeOutput.log".
See also "/root/sdr/src/volk/build/CMakeFiles/CMakeError.log".
```
Any help will be great. Thanks in advance

**Comment by n-west** [comment]
I think I fixed this in master by changing the initialization.
