### ISSUE TITLE
VOLK always assumes neon in arm builds. Also cmake needs updating to build for 32 and 64 bit arm

### ISSUE THREAD

**Issue by balister** [gnuradio/volk#175]
This is not always true.

For 32 bits build, cmake needs to inspect the flags passed to the compiler and see if -mfpu=neon is set. (Or do a compile time test), if this is true it should build and 32 bit neon assembly and arm intrinsics code.

If it is an aarch64 machine, it can assume 64 bit neon instructions. So build 64 bit asm and arm intrinsics.

32 and 64 bit neon asm is different, but the intrinsics work for both.

**Comment by michaelld** [comment]
@balister Is this still an issue? If so, what's a good approach to deal with it?

**Comment by jdemel** [comment]
Since we check for NEON presence in #319 and then for the correct version, I'd assume this issue is solved.
I propose to close it unless @balister says otherwise.

**Comment by michaelld** [comment]
Closing since there are no comments from the @balister gallery. Please reopen if this is still an issue, and explain what's going on so that we can address it!
