### ISSUE TITLE
let cmake prefer Py3k for builds

### ISSUE THREAD

**Issue by jdemel** [gnuradio/volk#195]
Since the latest VOLK version builds with Py3k, I suggest to make it the preferred Python version for `cmake`.

There are some advantages
- `Mako` seems to be installed by default on Ubuntu 18.04. Thus, it cuts dependency installs.
- Py3k was identified to be the future. So let's try to make the latest software the default and use everything else as a fallback. This might also be beneficial to flesh out bugs.

How do we get there? Let `cmake` prefer Py3k over Py2k.

**Comment by noc0lour** [comment]
We should definitively tell our downstream about that.

**Comment by michaelld** [comment]
I'd be game for this change. Doing so keeps Volk better aligned with GNU Radio changes in this regard, beyond other benefits.

**Comment by jdemel** [comment]
This issue is fixed with #306. Thus, I close this issue.
