### ISSUE TITLE
volk_32f_x2_pow_32f: fail on arch u_sse4_1

### ISSUE THREAD

**Issue by LazyDodo** [gnuradio/volk#20]
When compiling on windows with msvc test_all fails , initially I wrote this off to a compiler problem, however when digging deeper into the problem, it seems data related (test_all uses rand() to generate random data, which seem to use a different algorithm on windows). 

I extracted a small test case that's able to reproduce the problem on Linux/x64.

test code:

```
#include <volk/volk.h>
#include <stdio.h>

int main(int argc, char**argv)
{
                float a[] = { -0.852535, -0.864864, -0.100314, 0.871761};
                float b[] = { 0.510544, 0.148595, -1.000000, -0.196265};
                float generic_output[4];
                float sse4_u_output[4];

                volk_32f_x2_pow_32f_manual(generic_output, b,a, 4, "generic");
                volk_32f_x2_pow_32f_manual(sse4_u_output, b, a, 4, "u_sse4_1");
                for (int i = 0; i < 4; i++)
                {
                        printf("%f %f\n", generic_output[i], sse4_u_output[i]);
                }

                return 0;
}
```

output

```
Using Volk machine: avx_64_mmx
-nan 0.921084
-nan 0.978433
-9.968699 9.977540
1.027301 1.027618
```

**Comment by n-west** [comment]
This demonstrates two algorithmic issues with the sse4.1 and probably neon implementations.

1) Given an exponent of -1.0 we get the sign wrong
2) When the result is complex we need to return nan (or -nan?.
