### ISSUE TITLE
Volk build error

### ISSUE THREAD

**Issue by aligrt** [gnuradio/volk#201]
I received following error while building volk, any help please.

**[100%] Linking CXX executable volk_profile**
/usr/bin/ld: CMakeFiles/volk_profile.dir/volk_profile.cc.o: in function `boost::system::error_category::std_category::equivalent(std::error_code const&, int) const':
volk_profile.cc:(.text._ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei[_ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei]+0x30): undefined reference to `boost::system::detail::generic_category_instance'
/usr/bin/ld: volk_profile.cc:(.text._ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei[_ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei]+0x4e): undefined reference to `boost::system::detail::generic_category_instance'
/usr/bin/ld: volk_profile.cc:(.text._ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei[_ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei]+0x113): undefined reference to `boost::system::detail::generic_category_instance'
/usr/bin/ld: CMakeFiles/volk_profile.dir/volk_profile.cc.o: in function `boost::system::error_category::std_category::equivalent(int, std::error_condition const&) const':
volk_profile.cc:(.text._ZNK5boost6system14error_category12std_category10equivalentEiRKSt15error_condition[_ZNK5boost6system14error_category12std_category10equivalentEiRKSt15error_condition]+0x2d): undefined reference to `boost::system::detail::generic_category_instance'
/usr/bin/ld: volk_profile.cc:(.text._ZNK5boost6system14error_category12std_category10equivalentEiRKSt15error_condition[_ZNK5boost6system14error_category12std_category10equivalentEiRKSt15error_condition]+0x53): undefined reference to `boost::system::detail::generic_category_instance'
collect2: error: ld returned 1 exit status
make[2]: *** [apps/CMakeFiles/volk_profile.dir/build.make:117: apps/volk_profile] Error 1
make[1]: *** [CMakeFiles/Makefile2:295: apps/CMakeFiles/volk_profile.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by michaelld** [comment]
What version of Volk are you trying to build?
What version of Boost are you trying to build using?
What is your host OS & compiler?
How are you configuring Volk's CMake scripts for building?

**Comment by michaelld** [comment]
Given the lack of response, I'm closing this issue.
