### ISSUE TITLE
test_all fails on volk_32fc_x2_dot_prod_32fc_a_sse4_1 on windows.

### ISSUE THREAD

**Issue by LazyDodo** [gnuradio/volk#21]
Root cause is this initializer. 

https://github.com/gnuradio/volk/blob/master/kernels/volk/volk_32fc_x2_dot_prod_32fc.h#L314

Due to the way __m128i is defined on windows (by both the msvc and intel headers) the constant gets truncated and the sign flip never happens.

see this thread for details  https://gcc.gnu.org/ml/gcc-help/2009-04/msg00363.html

replacing neg with

```
__m128i neg = _mm_set_epi32(0,0,0,0x80000000);
```

fixes the issue.

**Comment by n-west** [comment]
This seems to be fixed in the referenced PRs
