### ISSUE TITLE
Wrong tarball prefix

### ISSUE THREAD

**Issue by csete** [gnuradio/volk#211]
Hi,

It looks like both volk 1.3.1 and 1.4 have been packaged with an incorrect prefix. I'm guessing that `git archive --prefix=volk-1.4` was used, instead of `git archive --prefix=volk-1.4/`

![screenshot_0076](https://user-images.githubusercontent.com/306178/47621038-1a1f4d80-daf2-11e8-91b6-722cbaf5f20b.png)

**Comment by jdemel** [comment]
Is this a duplicate of #177 ? If so, @csete could you close this issue? Maybe add some additional info to #177 .

**Comment by csete** [comment]
Indeed, it is the same issue, thanks.
