### ISSUE TITLE
volk_32f_s32f_convert_16i, sometimes zero result when misaligned?

### ISSUE THREAD

**Issue by ast** [gnuradio/volk#217]
```volk_32f_s32f_convert_16i``` seems to sometimes produce a {0} vector when output vector is misaligned on NEON. I'm a bit in the dark here but it would work perfectly on one Raspberry Pi 3 but produce a lot of {0} vectors on another (but not always).

When I changed the output vector from ```std::vector<int16_t>``` to using ```volk_malloc``` problem disappeared.

**Comment by noc0lour** [comment]
looks like this might be a bug in the unaligned kernel.

**Comment by ast** [comment]
Note: currently I'm using the version of libvolk that comes with raspbian so it might be out of date. What the best way to check version?

Not sure what other info I can supply. I'd be happy to try to build a test case with guidance.

**Comment by noc0lour** [comment]
`dpkg -l libvolk` could work?

**Comment by ast** [comment]
```
$ dpkg -l libvolk1.3 
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                   Version                  Architecture             Description
+++-======================================-========================-========================-==================================================================================
ii  libvolk1.3:armhf                       1.3-1+rpi1               armhf                    vector optimized functions```

**Comment by noc0lour** [comment]
ok, so it's the 1.3.1 release version

**Comment by noc0lour** [comment]
Hm, there is no neon implementation for that kernel? So the generic impl is failing?

**Comment by ast** [comment]
Very strange... Dispatcher bug?

I need to get started writing neon implementations... Is there a table/matrix over function vs missing implementations?

**Comment by noc0lour** [comment]
This: http://libvolk.org/platforms.html but needs updating for volk 1.4. @n-west how was that table generated?

**Comment by ast** [comment]
Never mind about this, I tracked this bug down to a different source. Sorry about that. Still interested in writing volk kernels for NEON though!

**Comment by ast** [comment]
I have started writing kernels. Would really like an updated list of missing NEON kernels!

**Comment by jdemel** [comment]
@ast Can we close this issue? Was your issue VOLK related? If this is not the case, we should close this issue here.

**Comment by ast** [comment]
We can close. I don't remember what caused it but it was not volk releated. Thanks for the push in merging PRs!

**Comment by jdemel** [comment]
@ast  Can you close this issue then, please?

**Comment by ast** [comment]
Closing as per discussion above.
