### ISSUE TITLE
volk_32u_reverse_32u.h: NEON uses `asm` instead of `__VOLK_ASM`

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/volk#219]
which leads to compilation issues, gnuradio/gnuradio#2192.

Potential solution: replace `asm` with `__VOLK_ASM`. Can't test.

**Comment by hcab14** [comment]
replacing `asm` with `__VOLK_ASM` and not explicitly using GNU compiler extensions (https://github.com/hcab14/volk/commit/e73179535d621e267e91f8cd2f31d799f3b2ea5f) does work, _i.e._, the CI tests on 32 and on 64-bit ARM architectures are passed (https://travis-ci.org/hcab14/volk)

**Comment by marcusmueller** [comment]
@hcab14 awesome! Thank you!

**Comment by nickoe** [comment]
@hcab14 has a pull request been made?

**Comment by hcab14** [comment]
Yes and it is merged into volk/master, see https://github.com/gnuradio/volk/pull/215

**Comment by nickoe** [comment]
@hcab14 ahh, ok, thank you. I just missed it because I could see a PR mentioned, and the volk submodule checked out in my gnuradio dir was not updated...

I guess this issue can be closed now then.

**Comment by hcab14** [comment]
AFAIC this issue can be closed .

**Comment by michaelld** [comment]
:+1:
