### ISSUE TITLE
volk_32f_s32f_convert_32i generic off by one.

### ISSUE THREAD

**Issue by ast** [gnuradio/volk#220]
Should be -2^31 and +2^31-1. Or have I gone crazy?

https://github.com/gnuradio/volk/blob/b459c6fb2ba1b3190dce9805035632ba176e0fab/kernels/volk/volk_32f_s32f_convert_32i.h#L416

**Comment by noc0lour** [comment]
So it should only be off-by-one if the float value is `-2^31`, right?  Probably it's safer to replace it with `INT32_{MIN,MAX}` anyway?

**Comment by ast** [comment]
INT{16,32}_{MIN,MAX} would be better.

**Comment by noc0lour** [comment]
Why INT16 in this case?

**Comment by ast** [comment]
Ah not it this case but in `volk_32f_s32f_convert_16i`.

**Comment by noc0lour** [comment]
Sure, I agree.

**Comment by ast** [comment]
What's the status of this @noc0lour @balister @marcusmueller.

Should we do a search and replace?

**Comment by jdemel** [comment]
This issue just got fixed with PR #298 . I guess we can close it now.

**Comment by michaelld** [comment]
Agreed!
