### ISSUE TITLE
MD5 usage causes build failure on FIPS enabled CentOS 7.4 system

### ISSUE THREAD

**Issue by awalls-cx18** [gnuradio/volk#238]
On a CentOS 7.4 system with FIPS mode enabled, the MD5 hash algorithm cannot be executed and building volk fails because of the use of MD5 here:

https://github.com/gnuradio/volk/blob/dd5e293c85975d4db6718aef685b1a15de88a74f/cmake/Modules/VolkPython.cmake#L117

Changing 'md5' to either 'sha1', 'sha256', or 'sha512' resolves the problem.

**Comment by Flamewires** [comment]
Believe I had the same issue happen in other places in gnuradio as well. Would be good to just switch all these to a newer hashing algorithm.

**Comment by n-west** [comment]
This seems like a minor change. Can you come up with a proposal and possibly a MR?

**Comment by michaelld** [comment]
better late than later ... ?
