### ISSUE TITLE
volk_profile selecting bad kernesl for the E310.

### ISSUE THREAD

**Issue by balister** [gnuradio/volk#25]
benchmark_{tx/rx} fail to tx/rx data using the result of running volk_profile. Removing volk_config (so you use all generic kernels work) Here are the diffs to volk_config I use to get teh flowgrpahs to work again.

For RX:

```
root@ettus-e300:~# diff volk_config .volk/volk_config
49c49
< volk_32fc_x2_multiply_32fc neon_opttests neon_opttests

---
> volk_32fc_x2_multiply_32fc neon neon
60c60
< volk_32f_x2_dot_prod_32f neonasm neonasm

---
> volk_32f_x2_dot_prod_32f neon neon
```

For TX:

```
root@ettus-e300:~# diff  volk_config .volk/volk_config
60c60
< volk_32f_x2_dot_prod_32f neonasm neonasm

---
> volk_32f_x2_dot_prod_32f neon neon
89c89
< volk_32fc_s32fc_multiply_32fc neon neon

---
> volk_32fc_s32fc_multiply_32fc generic generic
```

**Comment by n-west** [comment]
These kernels should be fixed in both maint and master. I found a few other bad apples that I also fixed. I'm going to use this as the volk code freeze and do a release. Holler if you want time to test before the release goes out.
