### ISSUE TITLE
problem compile gnuradio

### ISSUE THREAD

**Issue by tele1** [gnuradio/volk#27]
PCLinuxOS 64bit

I used:

%cmake
%make
%makeinstall_std

compiled volk 100% succes

problem is, gnu radio can not find volk
from gnu radio cmake I see, this search volk_common.h
volk_common.h is installed in
/usr/local/include/volk/volk_common.h

gnuradio $ cmake ..
...
CMake Error at CMakeLists.txt:310 (message):
  VOLK required but not found.

how fix it ?

macros :
$ rpm --eval=%cmake

  CFLAGS="${CFLAGS:--O2  -pipe -Wformat -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4}" ; export CFLAGS ; 
  CXXFLAGS="${CXXFLAGS:--O2  -pipe -Wformat -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4}" ; export CXXFLAGS ; 
  FFLAGS="${FFLAGS:--O2  -pipe -Wformat -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4}" ; export FFLAGS ; 
  LDFLAGS="$LDFLAGS -Wl,--as-needed -Wl,--no-undefined -Wl,-z,relro -Wl,-O1 -Wl,--build-id"; export LDFLAGS ; 
    mkdir -p build 
    cd build 

```
/usr/bin/cmake .. \
    -DCMAKE_INSTALL_PREFIX:PATH=/usr \
    -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64 \
    -DCMAKE_INSTALL_LIBEXECDIR:PATH=/usr/lib64 \
    -DCMAKE_INSTALL_SYSCONFDIR:PATH=/etc \
    -DINCLUDE_INSTALL_DIR:PATH=/usr/include \
    -DLIB_INSTALL_DIR:PATH=/usr/lib64 \
    -DSYSCONF_INSTALL_DIR:PATH=/etc \
    -DSHARE_INSTALL_PREFIX:PATH=/usr/share \
    -DCMAKE_BUILD_TYPE=release \
```

%if "lib64" == "lib64" 
        -DLIB_SUFFIX=64 \
%endif 
        -DCMAKE_SKIP_RPATH:BOOL=ON \
         \
        -DBUILD_SHARED_LIBS:BOOL=ON \
        -DBUILD_STATIC_LIBS:BOOL=OFF \
        -DCMAKE_MODULE_LINKER_FLAGS="-Wl,--as-needed  -Wl,-z,relro -Wl,-O1 -Wl,--build-id"

$ rpm --eval=%make
make -O -j4

$ rpm --eval=%makeinstall_std
make DESTDIR=/home/gg/src/rpm/BUILDROOT/%{name}-%{version}-%{release}.x86_64 install

Edit:
 export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
not helped.

Edit
Stable version gnuradio  3.7.7.1 from
http://gnuradio.org/releases/gnuradio/
working ! :dancers:   :+1:  

SOLVED

**Comment by n-west** [comment]
In the future, this is not the correct forum for installation help. This is for reporting issues related to the software. For help email the GNU Radio mailing list.

Also FYI: there's multiple ways to install VOLK + GNU Radio. I think you should have seen a message output from cmake instructing you to checkout a submodule. Alternatively since you had VOLK installed already you could have used the cmake option USE_INTERNAL_VOLK=Off

**Comment by tele1** [comment]
On 07/07/15 16:00, Nathan West wrote:

> In the future, this is not the correct forum for installation help. 
> This is for reporting issues related to the software. For help email 
> the GNU Radio mailing list.
> 
> Also FYI: there's multiple ways to install VOLK + GNU Radio. I think 
> you should have seen a message output from cmake instructing you to 
> checkout a submodule. Alternatively since you had VOLK installed 
> already you could have used the cmake option USE_INTERNAL_VOLK=Off
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/gnuradio/volk/issues/27#issuecomment-119211045.

Thanks,
now I see inside gnuradio volk, so I try disable volk :)
