### ISSUE TITLE
error building natively on USRP E310

### ISSUE THREAD

**Issue by jmodares** [gnuradio/volk#32]
libvolk.so.1.0.1: undefined reference to `volk_16i_max_star_horizontal_16i_neonasm'
libvolk.so.1.0.1: undefined reference to`volk_32f_x2_add_32f_neonasm'
libvolk.so.1.0.1: undefined reference to `volk_32fc_x2_multiply_32fc_neonasm'
libvolk.so.1.0.1: undefined reference to`volk_32fc_32f_dot_prod_32fc_a_neonasm'
libvolk.so.1.0.1: undefined reference to `volk_32f_x2_add_32f_neonpipeline'
libvolk.so.1.0.1: undefined reference to`volk_32f_x2_dot_prod_32f_neonasm'
libvolk.so.1.0.1: undefined reference to `volk_32fc_32f_dot_prod_32fc_a_neonasmvmla'
libvolk.so.1.0.1: undefined reference to`volk_32f_x2_dot_prod_32f_neonasm_opts'
libvolk.so.1.0.1: undefined reference to `volk_32fc_32f_dot_prod_32fc_a_neonpipeline'

**Comment by n-west** [comment]
This can be considered a bug, but it's also a known issue. This is not the appropriate place to discuss this or ask for help (try the mailing list). Also, if you google for the error you'll find the solution. BTW, I fixed this recently on maint anyway.
