### ISSUE TITLE
Incorrect function ranking?

### ISSUE THREAD

**Issue by ajraymond** [gnuradio/volk#33]
I am witnessing a strange behavior on my machine wrt arch ranking. I've narrowed it down to lib/volk_rank_archs.c:101.

The code does a popcnt on impl_deps, which contains 1 << various LV_{GENERIC,SSE4_1,AVX} constants, and picks the arch with the most 1s. However, since they are powers of two, they all get the same score.

Now, simply getting rid of popcnt solves the problem (as the best archs have a higher LV_ number), but I'm not sure that's the right thing to do

**Comment by n-west** [comment]
You're correct about this behavior. However, it's only a problem when you don't have a volk_config (generated by volk_profile). I removed the popcnt and will push a fix with the upcoming release.
