### ISSUE TITLE
add volk_version.h

### ISSUE THREAD

**Issue by michaelld** [gnuradio/volk#338]
Add `volk_version.h`, which sets macros

```
#define VOLK_VERSION_MAJOR @XX@
#define VOLK_VERSION_MINOR @YY@
#define VOLK_VERSION_PATCH @ZZ@
#define VOLK_VERSION @XX@@YY@@ZZ@
```
In this manner, any of these can be used for comparison in a macro. These will allow certain GR features to be fixed.

The actual XX YY ZZ will be set by CMake from a single point of version knowledge ... either to be created or existing.

**Comment by noc0lour** [comment]
This will enable downstream users like GNU Radio, to do simple `#ifdef` logic to circumvent buggy implementations!
