### ISSUE TITLE
Missing #include <arm_neon.h> in volk_16ic_s32f_deinterleave_32f_x2.h?

### ISSUE THREAD

**Issue by s2ack** [gnuradio/volk#35]
I have been using GNU Radio on Odroid XU3 (hardfp) with out issue but when I changed my development machine to from standard ubuntu 15.04 to xubuntu 15.04 Volk failed to compile.  Not sure if its my cross compiler environment (more than likely) but adding the missing #include arm_neon,h fixes the issue.

In file included from /work/arm/release/gnuradio-3.7.8rc1/build/volk/lib/volk_machine_neon_hardfp.c:39:0:
/work/arm/release/gnuradio-3.7.8rc1/volk/kernels/volk/volk_16ic_s32f_deinterleave_32f_x2.h: In function ‘volk_16ic_s32f_deinterleave_32f_x2_neon’:
/work/arm/release/gnuradio-3.7.8rc1/volk/kernels/volk/volk_16ic_s32f_deinterleave_32f_x2.h:152:3: error: unknown type name ‘float32x4_t’
   float32x4_t invScalar;

Fix below applied then everything is OK!
# ifdef LV_HAVE_NEON
# include &lt;arm_neon.h&gt;

static inline void
volk_16ic_s32f_deinterleave_32f_x2_neon(float\* iBuffer, float\* qBuffer, const lv_16sc_t\* complexVector,
                                        const float scalar, unsigned int num_points)
{

........
# endif

**Comment by n-west** [comment]
Thanks for the report. Let me know if you run in to any others. There's some evidence others might have the same problem just using grep and wc. I found one other file to fix with `grep LV_HAVE_NEON * -l | xargs grep arm_neon.h -L`
