### ISSUE TITLE
volk_32fc_s32fc_x2_rotator_32fc AVX kernel issues

### ISSUE THREAD

**Issue by michaelld** [gnuradio/volk#354]
As reported on Slack #gnuradio ... On GNU Radio 3.8.1rc1, on Ubuntu 20.04: audio is badly distorted. The culprit appears to be the volk_32fc_s32fc_x2_rotator_32fc AVX kernel. Reverting https://github.com/gnuradio/volk/pull/344 fixes the issue.

**Comment by michaelld** [comment]
So @jdemel we somehow messed the AVX kernel up in that PR. I'd prefer to fix it up rather than revert it ... so much good work in there! Do you have the bandwidth to look into this?

**Comment by jdemel** [comment]
That's a bummer. Is this related to the issue #329 ? And there is a start to increase precision in #341 .
I'd assume this would also happen with SSE. Can the issue be fixed with `VOLK_GENERIC`?
That would actually imply that we need more precision with this kernel. Also, it would point us in the right direction. 

If I recall correctly, the GR audio sink just got VOLKized. That does actually imply that we need more precision for this kernel. Smth we didn't really care for before.

**Comment by argilo** [comment]
The generic kernel works fine, as does the AVX FMA kernel.

**Comment by argilo** [comment]
I tested those cases by placing `volk_32fc_s32fc_x2_rotator_32fc generic generic` and then `volk_32fc_s32fc_x2_rotator_32fc a_avx_fma u_avx_fma` in my `.volk/volk_config`.

**Comment by argilo** [comment]
When i use `volk_32fc_s32fc_x2_rotator_32fc a_avx u_avx` the strong audio distortion occurs.

**Comment by argilo** [comment]
The problem can be reproduced like so:

![Screenshot from 2020-02-23 13-28-15](https://user-images.githubusercontent.com/583749/75117558-6aec7b00-5640-11ea-8a97-813374ed39c9.png)

![Screenshot from 2020-02-23 13-27-16](https://user-images.githubusercontent.com/583749/75117564-6de76b80-5640-11ea-826e-f209ef83fbce.png)

Interestingly, when the Audio Sink is removed, the discontinuities no longer appear in the Time Sink.

Perhaps some state being stored in a global variable?

**Comment by rear1019** [comment]
> Interestingly, when the Audio Sink is removed, the discontinuities no longer appear in the Time Sink.
> 
> Perhaps some state being stored in a global variable?

Try to replace the audio sink with a file sink/wav sink and play back the file by other means (i.e. do not use GNU Radio’s audio sink).

**Comment by argilo** [comment]
Actually the glitches do occur without the Audio Sink also, it seems I just wasn't patient enough.

**Comment by argilo** [comment]
A simpler flowgraph that can be used to reproduce it:

![Screenshot from 2020-02-23 13-50-39](https://user-images.githubusercontent.com/583749/75117887-8442f680-5643-11ea-9e69-5ec32e5254e4.png)

![Screenshot from 2020-02-23 13-50-35](https://user-images.githubusercontent.com/583749/75117889-860cba00-5643-11ea-8c4f-b145fdda2a00.png)

**Comment by argilo** [comment]
I think I found the bug. `num_points` should be `fourthPoints` here:

https://github.com/gnuradio/volk/blob/2cf27f3dcc048e34852ff1a9d3a7f21998ae9641/kernels/volk/volk_32fc_s32fc_x2_rotator_32fc.h#L530

**Comment by jdemel** [comment]
Thanks for hunting down this bug. I assume, we should put out a bugfix release for that. 2.2.1.

**Comment by argilo** [comment]
Yes, I think this should go into a bug fix release. Hopefully it's not too late to make it in before Ubuntu 20.04's Debian import freeze later this week.
