### ISSUE TITLE
18 - qa_volk_16ic_x2_dot_prod_16ic (Failed)

### ISSUE THREAD

**Issue by SignalWhisperer** [gnuradio/volk#384]
Similar issue as #382. I'm guessing the solution will be similar.
Running the commands as per the other issue:
```
$ ctest -VV -R x2_dot_prod
UpdateCTestConfiguration  from :/home/jd/source/volk/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/jd/source/volk/build/DartConfiguration.tcl
Test project /home/jd/source/volk/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 18
    Start 18: qa_volk_16ic_x2_dot_prod_16ic

18: Test command: /bin/sh "/home/jd/source/volk/build/lib/volk_16ic_x2_dot_prod_16ic_test.sh" "/home/jd/source/volk/build/lib"
18: Test timeout computed to be: 10000000
18: RUN_VOLK_TESTS: volk_16ic_x2_dot_prod_16ic(131071,1)
18: generic completed in 1.30312 ms
18: a_sse2 completed in 0.064963 ms
18: u_sse2 completed in 0.051387 ms
18: u_axv2 completed in 0.043813 ms
18: a_axv2 completed in 0.037481 ms
18: offset 0 in1: 3448 in2: -5774 tolerance was: 0
18: offset 1 in1: 2647 in2: -1393 tolerance was: 0
18: volk_16ic_x2_dot_prod_16ic: fail on arch u_axv2
18: offset 0 in1: 3448 in2: -5774 tolerance was: 0
18: offset 1 in1: 2647 in2: -1393 tolerance was: 0
18: volk_16ic_x2_dot_prod_16ic: fail on arch a_axv2
18: Best aligned arch: a_axv2
18: Best unaligned arch: u_axv2
1/4 Test #18: qa_volk_16ic_x2_dot_prod_16ic ....***Failed    0.01 sec
test 60
    Start 60: qa_volk_32f_x2_dot_prod_16i

60: Test command: /bin/sh "/home/jd/source/volk/build/lib/volk_32f_x2_dot_prod_16i_test.sh" "/home/jd/source/volk/build/lib"
60: Test timeout computed to be: 10000000
60: RUN_VOLK_TESTS: volk_32f_x2_dot_prod_16i(131071,1)
60: generic completed in 0.194837 ms
60: a_sse completed in 0.062517 ms
60: a_avx2_fma completed in 0.067287 ms
60: a_avx completed in 0.057749 ms
60: u_sse completed in 0.051096 ms
60: u_avx2_fma completed in 0.049273 ms
60: u_avx completed in 0.039614 ms
60: Best aligned arch: u_avx
60: Best unaligned arch: u_avx
2/4 Test #60: qa_volk_32f_x2_dot_prod_16i ......   Passed    0.01 sec
test 61
    Start 61: qa_volk_32f_x2_dot_prod_32f

61: Test command: /bin/sh "/home/jd/source/volk/build/lib/volk_32f_x2_dot_prod_32f_test.sh" "/home/jd/source/volk/build/lib"
61: Test timeout computed to be: 10000000
61: RUN_VOLK_TESTS: volk_32f_x2_dot_prod_32f(131071,1)
61: generic completed in 0.131317 ms
61: u_sse completed in 0.061446 ms
61: u_sse3 completed in 0.066034 ms
61: u_sse4_1 completed in 0.073869 ms
61: u_avx completed in 0.064982 ms
61: u_avx2_fma completed in 0.067697 ms
61: a_generic completed in 0.125186 ms
61: a_sse completed in 0.055875 ms
61: a_sse3 completed in 0.05333 ms
61: a_sse4_1 completed in 0.058911 ms
61: a_avx completed in 0.04748 ms
61: a_avx2_fma completed in 0.040386 ms
61: Best aligned arch: a_avx2_fma
61: Best unaligned arch: u_sse
3/4 Test #61: qa_volk_32f_x2_dot_prod_32f ......   Passed    0.02 sec
test 98
    Start 98: qa_volk_32fc_x2_dot_prod_32fc

98: Test command: /bin/sh "/home/jd/source/volk/build/lib/volk_32fc_x2_dot_prod_32fc_test.sh" "/home/jd/source/volk/build/lib"
98: Test timeout computed to be: 10000000
98: RUN_VOLK_TESTS: volk_32fc_x2_dot_prod_32fc(131071,1)
98: generic completed in 0.245924 ms
98: u_sse_64 completed in 0.145333 ms
98: u_sse3 completed in 0.136978 ms
98: u_sse4_1 completed in 0.180961 ms
98: u_avx completed in 0.130155 ms
98: u_avx_fma completed in 0.104727 ms
98: a_generic completed in 0.235944 ms
98: a_sse_64 completed in 0.091292 ms
98: a_sse3 completed in 0.09048 ms
98: a_sse4_1 completed in 0.162806 ms
98: a_avx completed in 0.091222 ms
98: a_avx_fma completed in 0.087926 ms
98: Best aligned arch: a_avx_fma
98: Best unaligned arch: u_avx_fma
4/4 Test #98: qa_volk_32fc_x2_dot_prod_32fc ....   Passed    0.04 sec

The following tests passed:
	qa_volk_32f_x2_dot_prod_16i
	qa_volk_32f_x2_dot_prod_32f
	qa_volk_32fc_x2_dot_prod_32fc

75% tests passed, 1 tests failed out of 4

Total Test time (real) =   0.09 sec

The following tests FAILED:
	 18 - qa_volk_16ic_x2_dot_prod_16ic (Failed)
Errors while running CTest
```

Here is my CPU (I have removed the other 15 entries as they are duplicates):
```
$ cat /proc/cpuinfo
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 8
model name	: AMD Ryzen 7 2700X Eight-Core Processor
stepping	: 2
microcode	: 0x800820d
cpu MHz		: 2068.633
cache size	: 512 KB
physical id	: 0
siblings	: 16
core id		: 0
cpu cores	: 8
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca
bugs		: sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 7385.33
TLB size	: 2560 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]
```

As per the other issue, removing the two lines containing `_mm256_zeroupper` causes the tests to pass.

I'm using gcc-10 from `ppa:ubuntu-toolchain-r/test`:
```
$ gcc --version
gcc (Ubuntu 10.1.0-2ubuntu1~18.04) 10.1.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by jdemel** [comment]
With #382 and #384 we have 2 very similar issues now.

In both cases recent GCC 9.3 and 10.1 are used. Two totally different but modern CPUs are affected. Does that also occur with clang?
I start to suspect that a recent change in GCC might trigger this bug.

We still need to figure out the root cause because removing these lines potentially affects performance.

**Comment by SignalWhisperer** [comment]
After building clang from source, I can confirm the tests pass at 100%.

```
$ bin/clang --version
clang version 11.0.0 (https://github.com/llvm/llvm-project.git 1d4c87335d5236ea1f35937e1014980ba961ae34)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/jd/source/llvm-project/build/bin
```

**Comment by karel** [comment]
Using clang 10.0.0 prevents this issue also, as opposed to GCC 10.1.0

**Comment by segevmalool** [comment]
I was getting this error as well. Tried installing clang from source (llvm-project) and it fixed it. Here're some detail about my env:

```
...
134/134 Test #134: qa_volk_8u_x4_conv_k7_r2_8u ..........................   Passed    0.00 sec

100% tests passed, 0 tests failed out of 134

Total Test time (real) =   2.86 sec
[segev@boss build]$ hostnamectl
   Static hostname: boss
         Icon name: computer-desktop
           Chassis: desktop
        Machine ID: 74947848896d4866b62e9ef6e63df015
           Boot ID: cb495f86587d43f5b907fa49085e1c93
  Operating System: Arch Linux
            Kernel: Linux 5.9.13-arch1-1
      Architecture: x86-64
[segev@boss build]$ clang --version
clang version 12.0.0 (https://github.com/llvm/llvm-project 1e785e92624b758e0d0bfe0efe3b4e6d1c44d27c)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin

```

The cmake output confirmed it was using the correct clang.

**Comment by jdemel** [comment]
So, with GCC 10 (+?) we see an issue with `_mm256_zeroupper`. Just to summarize the issue.

From the [Intel Intrinsics Guide](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=zeroupper&expand=6191)
```
void _mm256_zeroupper (void)
#include <immintrin.h>
Instruction: vzeroupper
CPUID Flags: AVX
```
Still, I don't have a clue why this might happen.

**Comment by rear1019** [comment]
I can reproduce this with GCC 10.2 [1] when building in `Release` mode (`-O3`). The compiler produces wrong code: Upper elements of `result = _mm256_or_si256(realcacc, imagcacc);` are used as if the explicit `zeroupper` is not present. The error does not occur with `RelWithDebInfo` (`-O2`).

* We should consider removing all explicit `zeroupper` calls. I am aware that this has performance implications. But so does the compiler which adds those calls automatically. This is controlled by `-mzerovupper` which is enabled by default [2].
* Am not convinced by the code produced for `16ic_x2_dot_prod_16ic` with `-O3`. It’s 3x bigger in terms of assembly instruction count and is not faster. But this is another issue to discuss…

[1] on Arch Linux and Ubuntu 20.04, packages from default repositories
[2] `gcc -Q -c -O2 -mavx2 --help=target` and `man gcc` imply it is not enabled by default, but using `-no-vzeropper` disables the generation of `vzeroupper`. Clang documentation implies it is enabled by default [3].
[3] https://releases.llvm.org/10.0.0/tools/clang/docs/ReleaseNotes.html#new-compiler-flags

**Comment by jdemel** [comment]
Does the switch `mzeroupper` change anything about the results?

These explicit `_mm256_zeroupper` calls are not followed by SSE intrinsics in this function. e.g. with godbolt it is easy to spot those automatically added zeroupper calls, thus calling them explicitly seems to be unnecessary. I get the impression that it is indeed necessary to remove them.

Thanks @rear1019 for gathering all the information!

**Comment by rear1019** [comment]
> Does the switch mzeroupper change anything about the results?

No, the same code is generated regardless whether `-mvzeroupper` is used or not. As noted before, it is enabled by default. The documentation of the flag is somewhat confusing, so I looked into it. The behavior as per [1] is:
* By default the compiler uses the `vzerovupper` instruction whenever this is deemed it necessary. Currently its usage is only disabled if the code is tuned for Intel’s Knight’s Landing CPU (`-mtune=knl`).
* Users can pass `-mvzeroupper` or `-mno-vzeroupper` to explicitly overwrite the compiler’s decision.

> These explicit _mm256_zeroupper calls are not followed by SSE intrinsics in this function. e.g. with godbolt it is easy to spot those automatically added zeroupper calls, thus calling them explicitly seems to be unnecessary. I get the impression that it is indeed necessary to remove them.

See above. TLDR: Trust the compiler to do the right thing. (Oh the irony…)

I'll make a PR shortly.

[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=82941#c3 (~2 years old, however, it still applies as far as I can tell after looking into GCC’s source code).
