### ISSUE TITLE
volk_32f_s32f_convert_8i behaviour differs between arm and x64

### ISSUE THREAD

**Issue by matburnham** [gnuradio/volk#390]
As detailed in https://github.com/gnuradio/gnuradio/issues/3571 it appears that `volk_32f_s32f_convert_8i` does not work as expected on ARM. The behaviour differs from that experienced in x86_64, and appears to unintentionally truncate negative values to zero.

**Comment by jdemel** [comment]
This is really surprising! Especially given the fact that this kernel does not have a NEON kernel. For ARM, we just use the generic kernel.
Having said that, this is the function:
https://github.com/gnuradio/volk/blob/e564299446a974ee48e30ffc36ee9d443633b9bc/kernels/volk/volk_32f_s32f_convert_8i.h#L283-L296
which then just calls:
https://github.com/gnuradio/volk/blob/e564299446a974ee48e30ffc36ee9d443633b9bc/kernels/volk/volk_32f_s32f_convert_8i.h#L79-L90
for every element. Looking at these functions, it is less surprising that it fails. `CHAR_MIN` is probably never what one would want it to be.  We use [inttypes.h](https://en.cppreference.com/w/c/types/integer) to choose the correct min/max values. But fail to get the correct ones for ARM. I assume, we can fix this by replacing `CHAR_` with `INT8_`.
