### ISSUE TITLE
auto format cmake files

### ISSUE THREAD

**Issue by jdemel** [gnuradio/volk#423]
I suggest to use [cmake_format](https://github.com/cheshirekow/cmake_format) to auto-format all our CMake files. cmake is often hard to read and having it at least formatted would ease this task. Of course, we'd need to decide on any particular style guide. etc.

**Comment by drmpeg** [comment]
I'm not sure how well supported this tool is. I tried to install it and was not successful. There's more than one complaint about this in the cmake_format Github issues, and no response.

https://github.com/cheshirekow/cmake_format/issues/238

https://github.com/cheshirekow/cmake_format/issues/234

**Comment by jdemel** [comment]
I'm aware that this is not perfect. Unfortunately, it is the only tool I found that does CMake formatting. Of course, I'd be happy to use a better tool. Do you happen to know one?

**Comment by jdemel** [comment]
This is essentially the same Issue as #600 . Since GR used it, we might follow.
