### ISSUE TITLE
Tarballs do not contain the cpu_features subdirectory

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/volk#426]
The auto-generated tarballs do not contain said directory. You get the not-so-helpful "run git submodule update --init" message, which of course won't work if you're not in a git repo.

**Comment by jdemel** [comment]
Oh. Where did this happen? I updated the 2.4.0 and 2.4.1 tarballs to contain this subfolder. The error message should be helpful for people that try to use VOLK via git clone and forgot to do so recursively.

**Comment by marcusmueller** [comment]
They do contain the subdirectory, but the detection fails when you build with `cmake -S <path to source> -B <path to build>` 

Which, sadly, our buildbot containers do ---

**Comment by marcusmueller** [comment]
no, that's not even the issue: it doesn't work when the build directory isn't a subdirectory of the source directory for some reason?

**Comment by marcusmueller** [comment]
what. not even that was the problem. (don't worry, I'll condense this flow of conscience down later)

**Comment by marcusmueller** [comment]
@mbr0wn when using the github automatic archive URL, you get an unsigned tarball that github rolled automatically. Using the VOLK releases page, everything seems peachy; https://github.com/gnuradio/volk/releases/download/v2.4.1/volk-2.4.1.tar.gz != https://github.com/gnuradio/volk/archive/v2.4.1.tar.gz

**Comment by jdemel** [comment]
So, my manually created tarball:  https://github.com/gnuradio/volk/releases/download/v2.4.1/volk-2.4.1.tar.gz  works correctly? But the GH auto generated one fails?

**Comment by jdemel** [comment]
@mbr0wn I assume we can't fix GH auto-generated files. I close this issue now. If my assumption is incorrect feel free to re-open this issue.
