### ISSUE TITLE
Consistent function prototypes are not enforced

### ISSUE THREAD

**Issue by rear1019** [gnuradio/volk#431]
While working on #368 I ended up using an inconsistent function prototype:
```c
volk_32fc_index_max_16u_a_avx2(uint32_t* target, lv_32fc_t* src0, uint32_t num_points)
```
instead of the required
```c
volk_32fc_index_max_16u_a_avx2(uint16_t* target, lv_32fc_t* src0, uint32_t num_points)
```
Note the different data type of the first argument.

This error has been detected by the compiler which issued a warning. We should consider doing at least one of the following:
* Turn `-Wincompatible-pointer-types` and possibly `-Wpointer-sign` warnings into errors.
* Check the prototypes in the generator scripts. I have written some code for this.

**Comment by jdemel** [comment]
I like that suggestion. Did you run a test how many kernels need to be fixed or which kernels need to be fixed if we activate that switch?

**Comment by rear1019** [comment]
> I like that suggestion. Did you run a test how many kernels need to be fixed or which kernels need to be fixed if we activate that switch?

None. `-Wincompatible-pointer-types` is a warning enabled by default. `-Wpointer-sign` is enabled by `-Wall` (which we do enable). See PR #433 which makes these warnings errors.
