### ISSUE TITLE
accumulate_square_sum does not compile on ARMv7 CI

### ISSUE THREAD

**Issue by jdemel** [gnuradio/volk#471]
I just stumbled across this CI failure:
https://travis-ci.com/github/gnuradio/volk/jobs/502050291
This is something that needs to be investigated.

**Comment by jdemel** [comment]
@Ka-zam would you mind to have a look at this issue? The problematic function is

https://github.com/gnuradio/volk/blob/79a111ba600c86ae937830970b00ebe0c711df5a/include/volk/volk_neon_intrinsics.h#L280-L290

which can't build on armv7.

**Comment by drmpeg** [comment]
Verified on native build.

**Comment by jdemel** [comment]
The issue was fixed in the linked and merged PR. Closing this issue now.
