### ISSUE TITLE
Relicense VOLK under LGPL

### ISSUE THREAD

**Issue by jdemel** [gnuradio/volk#492]
**EDIT** [GREP 23](https://github.com/gnuradio/greps/blob/master/grep-0023-relicense-volk.md) describes the intention in detail.

VOLK is migrating from GNU General Public License v3.0 or later (GPL-3.0-or-later) to GNU Lesser General Public License v3.0 or later (LGPL-3.0-or-later).

**Please support us in this effort to re-license VOLK. This is really a long-standing community wish.**

We need to collect re-submissions from all contributors to do so. We might be forced to remove commits that are not resubmitted.

How to re-submit your contributions:
You don't need to start a PR with all your previous commits. You only need to clearly state that you want to an can re-submit your contributions.

We collect a list of all contributors that resubmitted their code in [AUTHORS_RESUBMITTING_UNDER_LGPL_LICENSE](https://github.com/gnuradio/volk/blob/main/AUTHORS_RESUBMITTING_UNDER_LGPL_LICENSE.md).

How do I add myself to this list?

1. Open a PR that adds yourself to the list. Use the suggested wording in your git commit message **Preferred**
2. Write an email to the maintainers, Michael Dickens or Johannes Demel, that clearly states your wish to be added to the list. We will add the email contents to the corresponding git commit that adds your name to the list.
3. Add a comment to this issue 

In order to make things easier for everyone, we prepared a statement that only needs your info
- your name that you used for your commits.
- your GitHub handle (helps us identify commits)
- your email address(es) that you used for your commits. Again to identify commits.

Suggested wording:
> I, {contributor name}, hereby resubmit all my contributions to the VOLK
project and repository under the terms of the LGPL-3.0-or-later.
My GitHub handle is {github handle}.
My email addresses used for contributions are: {email address}, ... .
> 
> I hereby agree that contributions made by me in the past, to previous
versions of VOLK, may be re-used for inclusion in VOLK 3. I understand
that VOLK 3 will be relicensed under LGPL-3.0-or-later.

**Comment by michaelld** [comment]
To folks reading this issue, and to clarify one point: Your relicensing information submitted in any form _must_ contain some variant on the `Suggested wording` noted above -- though it's easiest to use that language instead of creating your own. If submitting a PR, then the language can be in the commit or in the PR itself. Just changing the noted file (`AUTHORS_RESUBMITTING_UNDER_LGPL_LICENSE`) is _not_ enough. We need your _explicit_ relicensing approval; being explicit is _the_ major key here. Without your explicit approval in writing, we cannot accept your changes to the relicensing file. Thanks for you attention to this seemingly minor detail.

**Comment by Teque5** [comment]
All code written by The Aerospace Corporation (including all @aero.org email addresses) was released to the GNU Radio project per our prior signed CLA. As such we have no issue with VOLK as a GNU Radio subproject re-licencing that code as LGPL. As a company we prefer to release as LGPL or GPL when possible.

**Comment by michaelld** [comment]
@Teque5 Thanks for that note. I find these email addresses in the GIT log: `damian.miralles@aero.org` and `jessica.iwamoto@aero.org`. It's not clear that either of those folks work for The Aerospace Corporation any longer, so a blanket approval is an option so long as whoever is doing the approval has the authority to do so. It looks from your GitHub profile that you do work there currently, correct? If that is the case, then there are 3 options for proceeding that I can think of: (1) each individual noted does relicensing via a PR as noted above. (2) You create a PR that notes all of the people working for The Aerospace Corporation as listed along with your note above, a blanket statement covering all of The Aerospace Corporation. (3) I/we create the PR and you, representing The Aerospace Corporation, approve of it. Preferences?

**Comment by Teque5** [comment]
> It looks from your GitHub profile that you do work there currently, correct?

Myself and another engineer essentially _own_ and manage the company's presence on GitHub.

> If that is the case, then there are 3 options for proceeding

I thought that my comment above satisfies your (2) without creating a PR. I can make a PR if you like but it will say the same thing as that comment.

**Comment by michaelld** [comment]
@Teque5 hmmm ... well we need a PR that adds the info to the relicensing file and clearly states the intent of the relicensing. My suggestion is that you do the PR & augment the `AUTHORS_RESUBMITTING_UNDER_LGPL_LICENSE.md` file with the following line:
```
| 2021-09-30 | The Aerospace Corporation |  Teque5 {, others} |  damian.miralles@aero.org, jessica.iwamoto@aero.org {, others} |
```
and add your own email and/or the email for your GitHub account as well as other GitHub accounts used that you know of.

Then in the commit message use the following language:
```
I, {contributor name} as an authorized representative of The Aerospace Corporation ("Aero.org") on behalf of all Aero.org contributors, hereby resubmit all of our contributions to the VOLK project and repository under the terms of the LGPL-3.0-or-later. GitHub handles associated with Aero.org contributors include but might not be limited to: Teque5 {, others}. Email addresses used for contributions include but might not be limited to: damian.miralles@aero.org, jessica.iwamoto@aero.org {, others}.

I, on behalf of all Aero.org contributors, hereby agree that contributions made by Aero.org in the past, to previous versions of VOLK, may be re-used for inclusion in VOLK 3. I understand that VOLK 3 will be relicensed under LGPL-3.0-or-later.
```

**Comment by jdemel** [comment]
@Teque5 We just received #537 . Would this help you as a template?

**Comment by michaelld** [comment]
@Teque5 As a followup to @jdemel 's comment: We need a blanket statement from aero.org that is traceable back to someone of authority within the organization. A named someone, as is the person inside NI for #537 . [Individuals do not need to meet this requirement, though only a few have requested specifically to not be named.] It took me quite a bit of work to find this person; I had to go through multiple different people within multiple different groups including planning and legal to get permission and then approval. If you feel that you have authority on behalf of aero.org to do the relicensing, then please do & let's just get this done. If you feel, like me, that you need to go through your legal & other channels, then I'd invite you to please get that process started sooner than later; it takes time, but I think the end result will be what we're all hoping for. Once you get to the point of approval (wether you or via some other person), then you can just send us an email with the statement roughly as noted above (and/or as per the noted PR). I'd be happy to discuss this more via email ( michael.dickens@ettus.com ). Thank you!

**Comment by hcab14** [comment]
I, Christoph Mayer, hereby resubmit all my contributions to the VOLK
project and repository under the terms of the LGPL-3.0-or-later.
My GitHub handle is `hcab14`.
My email addresses used for contributions are: hcab14@gmail.com, Christoph.Mayer@cern.ch.

I hereby agree that contributions made by me in the past, to previous
versions of VOLK, may be re-used for inclusion in VOLK 3. I understand
that VOLK 3 will be relicensed under LGPL-3.0-or-later.

**Comment by michaelld** [comment]
Thank you @hcab14 !

**Comment by jdemel** [comment]
With #577 we just added the last person to the list. Thus, we're ready to go ahead with a VOLK 3.0 release under LGPL.

**Comment by jdemel** [comment]
Being technical: There are 3 people left (out of 74) who we haven't been able to get in contact with (at all), for a total of 4 (out of 1092) commits, 13 (of 282822) additions, and 7 (of 170421) deletions. We have reviewed these commits and all are simple changes (e.g., 1 line change) and most are no longer relevant (e.g., to a file that no longer exists). Volk maintainers (@michaelld  and @jdemel) are in agreement that the combination -- small numbers of changes per committer, simple changes per commit, commits no longer relevant -- means that we can proceed with relicensing without the approval of the folks. We will try reaching out periodically to these folks, but we believe it unlikely we will get a reply.

**Comment by michaelld** [comment]
Totally agree with what @jdemel wrote, which is good ;)
