### ISSUE TITLE
Links to 2.5.0 release in website broken

### ISSUE THREAD

**Issue by aleksander0m** [gnuradio/volk#546]
The https://www.libvolk.org/releases.html page lists all releases of the library, but all the links related to the 2.5.0 release are broken: 

https://www.libvolk.org/releases/volk-2.5.0.tar.gz
https://www.libvolk.org/releases/2.5.0.sha256.sig
https://www.libvolk.org/releases/volk-2.5.0.tar.gz.asc

**Comment by jdemel** [comment]
Thanks for pointing this out! I just fixed it.
