### ISSUE TITLE
deprecate untested kernels

### ISSUE THREAD

**Issue by jdemel** [gnuradio/volk#549]
VOLK includes kernels that are untested.

https://github.com/gnuradio/volk/blob/0e844c6115f8e2cda5646a45f6162482c32eef8d/lib/kernel_tests.h#L169-L178

- volk_16i_x5_add_quad_16i_x4 
- volk_16i_branch_4_state_8
- volk_16i_max_star_16i
- volk_16i_max_star_horizontal_16i
- volk_16i_permute_and_scalar_add
- volk_16i_x4_quad_max_star_16i

I suggest to deprecate them and remove them in a future VOLK version. However, I suggest to check if GNU Radio uses them anywhere. If these kernels are still in use, we should re-introduce them into our CI and make sure they properly describe what they're doing.

**Comment by michaelld** [comment]
Agreed all around! All Volk kernels need at least some basic test, and preferably something useful. If we don't have tests and the kernel isn't being used, then let's deprecate it now & remove it shortly.
