### ISSUE TITLE
test_params output scaled with 2*pi since sin/cos kernel issue

### ISSUE THREAD

**Issue by stwunsch** [gnuradio/volk#56]
Hi,

Since the sin/cos issue the test_params are scaled with 2*pi (see qa_utils.cc:25). This is not an intuitive choice. Probably it would be better to change it back to (-1,1) as written in the comment and write a puppet for the sin and cos kernels.

Or should the test_params be able to scale the input directly by a parameter?

If the puppets are the desired solution, I can submit a pull request, this is not much work

Greetings

**Comment by n-west** [comment]
I think this can be fixed as part of a slight refactor of how QA is done. These kernels don't really need a puppet to do this. You are correct that the default should revert back to -1 to 1
