### ISSUE TITLE
Make Failure after Building target pygen_python_volk_modtoo_79139

### ISSUE THREAD

**Issue by AstroP25** [gnuradio/volk#569]
Failure in the compiling process with the error:

```
/usr/bin/ld: //usr/local/lib64/libcpu_features.a(impl_x86_linux_or_android.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
```

Cmake version 3.20.2
Make version  4.2.1
Red Hat Enterprise Linux 8.5

**Comment by jdemel** [comment]
Welcome @AstroP25 

Could you add some more info to your bug report? 
Which VOLK version do you try to compile?
The error indicates that linking against cpu_features failed.
Which options did you use to compile VOLK?
Which version of cpu_features do you use?
Is it correct to assume that you use GCC 8.2?

**Comment by AstroP25** [comment]
No problem.

VOLK version is 2.5.1 and the version of cpu_features is the submodule included in the git clone --recursive which appears to be 0.7.0. Currently running the default options to compile VOLK. 

GCC version is 8.5.0 20210514

**Comment by jdemel** [comment]
This sounds like an issue where `cpu_features` is built without `CMAKE_POSITION_INDEPENDENT_CODE ON`.
It would probably be helpful to see the CMake output and try to find the issue there.
One more observation: `/usr/local/lib64/libcpu_features.a(impl_x86_linux_or_android.c.o)`. It looks like there's a `cpu_features` version installed already. This might be another issue for the linker.

**Comment by jdemel** [comment]
@AstroP25 does the latest VOLK version on `main` fix your issue? Did you find out how to fix it? I suggest we close this issue if it is solved.

**Comment by jdemel** [comment]
We improved the situation with `cpu_features` over the last couple of months. I'm closing this issue now. Feel free to re-open it, in case this is still an issue.
