### ISSUE TITLE
Prepare and release VOLK 3.0

### ISSUE THREAD

**Issue by jdemel** [gnuradio/volk#581]
We mostly finished #492, aka VOLK re-licensing.

This issue is intended to track work in preparation of a VOLK 3.0 release. VOLK 3.0 is intended to be the first LGPL-only release. Right before that we will see a final 2.x release.

This is a list of things, we need to do before the release.

1. Fixup SPDX license identifiers. In the end, we want to be able to run a simple find and replace to make sure that VOLK 3.0 has the correct LGPL header everywhere. This update is split into multiple PRs: 
 - #583
 - #584
 - #585
 - #586
 - #587
 - #588
 - #591 
 - The folders `docs/` and `scripts/` did not receive any update. They are skipped intentionally.
3. Re-organize the top-level folder. This was already started in #580 .
4. Move Doxygen related CMake code and files into the `docs/` folder. cf. #582 
5. Have a final VOLK 2.x release.
6. Clean-up the license files.
7. Have a first VOLK 3.0 release that is LGPL-only.

I'm aware that there are long-standing issues that would require an API change. However, fixing these issues appropriately is a long process. I want to make sure, we do the license API change as soon as possible and the the "license-limbo".

**EDIT**
I added references to more PRs that address parts of this issue.

**Comment by michaelld** [comment]
What shall we do about copyright statements? Both the years as well as the copyright owner? Does FSF still own the copyright? I thought GR is now under SETI?

I like what GR has done for the years ... from the top level README:
```
## Legal Matters

Some files have been changed many times throughout the years. Copyright
notices at the top of source files list which years changes have been
made. For some files, changes have occurred in many consecutive years.
These files may often have the format of a year range (e.g., "2006 - 2011"),
which indicates that these files have had copyrightable changes made
during each year in the range, inclusive.
```

**Comment by jdemel** [comment]
It'd be a huge effort to update all the copyright years in every file. Obviously, we'd need to have a script to automate that.
As far as I know, GR kept the old copyright notices and only new commits receive individual copyright entries. However, we re-license VOLK. Everyone re-submitted their code. How does that change things?

**Comment by michaelld** [comment]
Yes redoing the (C) years would need to be automated. Not sure it's worth it. Was more wondering if we should, moving forward, go to either: (1) just use the initial creation year, since (C) is good for a long time & we will not be around when that time comes; (2) use ["creation year" - "latest change year"] to be inclusive of all possible changes for the given file; (3) just use "current year". IDK which is better / best / worst, but since we're going all this work we can determine a reasonable path forward, and then go with it.

**Comment by michaelld** [comment]
(4) stick with what we have ...
