### ISSUE TITLE
Kernel name with leading x character throws exception

### ISSUE THREAD

**Issue by stwunsch** [gnuradio/volk#59]
Hi,

A kernel with the name volk_32f_x2_x<sth>_32f throws an exception during ctest. The problem is simply a leading x in the kernel name "x<sth>", which looks like the "x<number>" of the input signiture.
If this is known and intended, just close the issue!

Greetings
Stefan

**Comment by stwunsch** [comment]
I mean this exception in qa_utils.cc:376:

```
catch (boost::bad_lexical_cast& error) {
    std::cerr << "Error: unable to get function signature from kernel name" << std::endl;
    std::cerr << "  - " << name << std::endl;
    return false;
}
```

**Comment by n-west** [comment]
Hey Stefan, not intended but not something anyone has complained about. If the fix is as easy as I think it might be I can fix it, otherwise it's kind of a niche feature (especially the _x_ case) that it might be a do not fix.

**Comment by douggeiger** [comment]
I'm guessing this is the signature parsing code not knowing when it's parsing signatures (ala _x2_ or _x3_ to signify multiple inputs of the same type) vs. when it is getting to the name of the kernel. I'm not confident there is an unamiguous way for the parser to know this in advance - except to check if the second character is a digit or not - which basically just makes x[0-9]+ a special (not-allowed at the beginning of the name) vs. just x\* being special.

**Comment by n-west** [comment]
Fixed

**Comment by ValZapod** [comment]
`(token[1] > '0' || token[1] < '9')`
@michaelld There should be && in this commit.

**Comment by michaelld** [comment]
@ValZapod Let's take the discussion to this issue https://github.com/gnuradio/volk/issues/326

**Comment by ValZapod** [comment]
@michaelld https://github.com/gnuradio/volk/issues/59#issuecomment-166156861 Here it is said x[0-9]
