### ISSUE TITLE
volk 3.0.0: GPL to LGPL changed not everywhere, e.g. in some *.cmake.in and CMakeLists.txt files

### ISSUE THREAD

**Issue by mobius217** [gnuradio/volk#613]
Run command:
grep -r -F " GPL-3" *
and see:
apps/CMakeLists.txt:# SPDX-License-Identifier: GPL-3.0-or-later
cmake/cmake_uninstall.cmake.in:# SPDX-License-Identifier: GPL-3.0-or-later
cmake/Modules/VolkConfig.cmake.in:# SPDX-License-Identifier: GPL-3.0-or-later
cmake/Modules/VolkConfigVersion.cmake.in:# SPDX-License-Identifier: GPL-3.0-or-later
CMakeLists.txt:# SPDX-License-Identifier: GPL-3.0-or-later
docs/CMakeLists.txt:# SPDX-License-Identifier: GPL-3.0-or-later
include/volk/volk_version.h.in: * SPDX-License-Identifier: GPL-3.0-or-later
lib/CMakeLists.txt:# SPDX-License-Identifier: GPL-3.0-or-later
lib/constants.c.in: * SPDX-License-Identifier: GPL-3.0-or-later
python/volk_modtool/CMakeLists.txt:# SPDX-License-Identifier: GPL-3.0-or-later

**Comment by jdemel** [comment]
@mobius217 Thanks for the report!

Out of curiousity: How do you use VOLK?

**Comment by mobius217** [comment]
> Out of curiousity: How do you use VOLK?

I am considering VOLK for one of my future personal projects.
Thanks for VOLK!!!
