### ISSUE TITLE
Debug message contaminates standard out

### ISSUE THREAD

**Issue by vsergeev** [gnuradio/volk#66]
The "Using Volk machine:" message https://github.com/gnuradio/volk/blob/v1.2.1/tmpl/volk.tmpl.c#L56 contaminates stdout, which interferes with programs that are trying to use that as a channel for structured data (e.g. JSON, etc.).

Could this message be moved to standard error, or even omitted altogether, since `volk_get_machine()` already provides this information in the public API?

**Comment by vsergeev** [comment]
#48 or similar would address this.

**Comment by n-west** [comment]
I'm on board with directing messages like this somewhere other than stdout by default, but don't think that PR is the right approach. I'd like to see a very lightweight logging framework, probably compile time configurable.

**Comment by vsergeev** [comment]
Sounds good to me. At the moment (v1.2.2), it seems that volk only has only two active call sites to `printf()` -- `get_machine()` (https://github.com/gnuradio/volk/blob/v1.2.2/tmpl/volk.tmpl.c#L35), and `volk_get_index()` (https://github.com/gnuradio/volk/blob/v1.2.2/lib/volk_rank_archs.c#L41) -- that are triggered through use of the library. In the meanwhile, wouldn't it be prudent to move these messages (2 lines of code) to stderr, or even omit them altogether, while the better logging approach is being developed? I can provide a PR if this is reasonable.

EDIT: The message in `volk_get_index()` is exceptional, so it seems that it's only the one message in `get_machine()` that is a culprit.
