### ISSUE TITLE
volk_malloc should not printf

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/volk#666]
`volk_malloc` is a service routine; not being able to allocate memory is unfortunate, but just like normal `libc` malloc, the consumer needs to check whether an allocation worked, either way. The "printf debugging" shouldn't be "normally on", as a library shouldn't do freaky things to a user's stderr on its own – *especially* not using `fprintf` in an environment where output buffering might already be handled by the C++ runtime to begin with.

**Comment by jdemel** [comment]
I assume you refer to:
https://github.com/gnuradio/volk/blob/fe463375f72170a56254bfc5bd2bfc6872828dd9/lib/volk_malloc.c#L41
and other occurrences of `fprintf` in that file and function.
As far as I remember, it's always been there.

I could imagine that simply removing the `fprintf` lines would be reasonable.
