### ISSUE TITLE
Consider to compile generic kernels into arch specific versions

### ISSUE THREAD

**Issue by jdemel** [gnuradio/volk#670]
Compilers are very smart nowadays. In a lot of cases, the compiler will produce more performant code than we can hand-optimize.

VOLK provides different important mechanisms.
1. hand-optimized kernels
2. an architecture agnostic interface
3. infrastructure to compile kernels for specific architectures cf. `-mavx2`
4. infrastructure to detect and load the best performing kernel on specific hardware.

We can use this interface and the infrastructure, keep all the kernels, and use a good benchmark.
Our benchmark would be "Are we better than the compiler optimizing for specific hardware"?

If we don't have an implementation for a specific architecture available, we can still leverage whatever the compiler can do.

**Comment by marcusmueller** [comment]
would this be as simple as making our build infrastructure copy every `_generic` kernel to a new `_generic_${MACHINENAME}` kernel, and compile it for that target machine?

**Comment by marcusmueller** [comment]
hm, I'm trying this, and interestingly, generic kernels and the same C code copied into …_avx2 kernels have at least in my sample (magintude_squared), very very similar runtimes.

I need to look at the disassembly, but chances are, GCC13 and clang16 are both not bad at optimizing code that leads to efficient microcode execution on a range of archs?

Need to check different intel gens.

**Comment by marcusmueller** [comment]
scratch that. @jdemel  I think this is already happening. If you look through `objdump -t libvolk.so`, you'll see the same `xyz_generic` symbol occur multiple times. Some are plain baseline code, others contain AVX512 instructions.

`objdump --disassemble libvolk.so`

**Comment by marcusmueller** [comment]
yeah, build/lib/CMakeFiles/volk_machine_${MACHINE_NAME}_.c.o already contains per-machine optimized generic kernels, so this is already implemented.

**Comment by jdemel** [comment]
Yes, it should be as simple as: Let the build system copy the generic kernel into every architecture specific compilation unit. That would be the idea.

**Comment by marcusmueller** [comment]
again, this is already happening.

**Comment by jdemel** [comment]
> again, this is already happening.

The compiler could probably generate these version under the hood. But we don't do this explicitly.

**Comment by marcusmueller** [comment]
Again, we do. We really really do. (please check the library as I illustrated above, you *will* find a compiled version of every generic kernel for every machine)

**Comment by jdemel** [comment]
Let me summarize this discussion.

1. We define a separate machine for each reasonable combination of SIMD extensions.
2. Every kernel that fits into a specific machine is compiled into it. e.g. an AVX2 machine includes all previous SSE versions and a generic version. This machine is compiled with `-msse -mavx2 ...`.
3. The generic kernel is included in every machine.
4. In effect we compile every generic kernel with every reasonable combination of SIMD extensions.
5. There's no need to generate `_generic_avx2` etc. kernels because we already do.

@marcusmueller thanks for digging this up.

Closing now as complete.
