### ISSUE TITLE
Truncate-toward-zero distortion in some kernels

### ISSUE THREAD

**Issue by argilo** [gnuradio/volk#673]
As noted in https://github.com/gnuradio/volk/issues/669#issuecomment-1774158247 and https://github.com/gnuradio/volk/issues/669#issuecomment-1774160329, the following kernels cast directly from `float` to an integer type:

* `volk_32f_x2_dot_prod_16i`
* `volk_32fc_s32f_deinterleave_real_16i`

The truncate-toward-zero of the cast introduces distortion, as noted here: https://www.cs.cmu.edu/~rbd/papers/cmj-float-to-int.html

Most kernels avoid this problem by applying `rintf` to round the floating-point number before conversion.

I have not checked whether any other integer-output kernels have this defect.

**Comment by jdemel** [comment]
The fix would be to introduce `rintf` in these two kernels as well.
Does this issue supersede #669 ?

**Comment by argilo** [comment]
> Does this issue supersede #669 ?

I don't think so. #669 is about the test tolerance, which will still need to be increased even if we switch to `rintf` for rounding.

**Comment by argilo** [comment]
> I have not checked whether any other integer-output kernels have this defect.

I checked over the rest, and didn't find any other kernels with distortion.

**Comment by n-west** [comment]
Since you're working on round, you might be interested in the implications of rintf (especially compared to std::round) which *might* be unexpected but standards-compliant https://x.com/nathanewest/status/1715095455376560344?s=20
