### ISSUE TITLE
64-bit integer testing is broken

### ISSUE THREAD

**Issue by argilo** [gnuradio/volk#681]
The `icompare` function casts all inputs to `int` before comparing & printing them. This prevents errors in upper bits from being caught, and makes it difficult to diagnose failures.

https://github.com/gnuradio/volk/blob/e853e9bb5693c7800840b736e77db52d713d553e/lib/qa_utils.cc#L463-L480

**Comment by jdemel** [comment]
We could use `long long int` [cf. Int types](https://en.cppreference.com/w/cpp/language/types).

However, the fundamental int types just feel broken.
I assume we should `#include <cstdint>` and use [fixed width integer types](https://en.cppreference.com/w/cpp/types/integer).

In this specific case `int64_t` would be correct. Though, this type is marked optional.

**Comment by jdemel** [comment]
If we change this line:
https://github.com/gnuradio/volk/blob/d5b317c17efd23f6c6cd9a52584123e1a7545452/lib/qa_utils.cc#L493
to
```cpp
if (((unsigned int)abs(int64_t(((t*)(in1))[i]) - int64_t(((t*)(in2))[i]))) > tol) { 
```
we should be good. Technically, a `#include <cstdint>` line is required as well.
