### ISSUE TITLE
lib/CMakeLists.txt: check_type_size("void*[8]" SIZEOF_CPU BUILTIN_TYPES_ONLY) empty

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/volk#683]
This leads to the folliowing cmake failure in a ninja/clang/Coverage build attempt

```
CMake Error at lib/CMakeLists.txt:248 (if):
  if given arguments:

    "EQUAL" "8"

  Unknown arguments specified
```

This checking seems redund, see CMAKE_SIZEOF_VOID_P.

**Comment by jdemel** [comment]
This is the line of code
https://github.com/gnuradio/volk/blob/e853e9bb5693c7800840b736e77db52d713d553e/lib/CMakeLists.txt#L241-L265

We should check if CMake introduced a check for CPU width. Also, this whole function seems to only apply to x86. The MSVC specific parts needs to stay anyways.
