### ISSUE TITLE
volk_32f_x2_dot_prod_32f missing MSVC compatible aligned var declaration when using AVX2 

### ISSUE THREAD

**Issue by gnieboer** [gnuradio/volk#70]
MSVC uses a different syntax for aligned data types, so when AVX2 is enabled, compilation will fail.  

See this [commit](https://github.com/gnuradio/volk/pull/68/commits/543d3d87b00ed596ea1d0b030107f05ea37801df) in [this](https://github.com/gnuradio/volk/pull/68) pull request for a patch that conditionally compiles the appropriate syntax.

Thought... if we expect introduction of a lot more aligned data types, you may want to define a generic macro in a header to avoid cluttering the code.  
# ifdef _MSC_VER
# define ALIGNED(WIDTH, VAR) _declspec(align(WIDTH)) VAR
# else
# define ALIGNED(WIDTH, VAR) VAR__attribute__((aligned(WIDTH)))
# endif

**Comment by guruofquality** [comment]
@gnieboer if you need alignment, use the __VOLK_ATTR_ALIGNED() macro from https://github.com/gnuradio/volk/blob/master/include/volk/volk_common.h

Use the __VOLK_ATTR_ALIGNED() macro before the declaration, and not at the end. Then it will work for both compilers with no ifdef

**Comment by gnieboer** [comment]
OK, didn't see there was already a macro in there.  Then definitely disregard my fix and simply replace said code with the macro.

**Comment by guruofquality** [comment]
@gnieboer I was just trying to help out and keep the patches clean and neat -- and hopefully easier for the maintainer to merge :-) I don't have a way to upstream the patch myself, so you should probably make the `__VOLK_ATTR_ALIGNED` change part of your pull request.

**Comment by gnieboer** [comment]
Agreed, clean is good.  Change made to pull request!

**Comment by n-west** [comment]
Is this still a problem? I think the appropriate PR was merged.
