### ISSUE TITLE
Automate docs generation and release

### ISSUE THREAD

**Issue by jdemel** [gnuradio/volk#750]
We use doxygen to produce our docs. We should be able to automatically build the docs and deploy them.
@noc0lour mentioned:
```yaml
  - run: 'tar -cz public | ssh $SSH_USER@$SSH_HOST "mkdir -p /www/$(date +%Y.%m.%d); cd /www/$(date +%Y.%m.%d); tar --strip-components=1 -xz; rm /www/live; cd /www; ln -sf $(date +%Y.%m.%d) live;"'
```
from: https://github.com/gnuradio/libvolk.org/blob/master/.circleci/config.yml

I suggest to regenerate the docs everytime a push/merge to `main` happens.

**Comment by noc0lour** [comment]
I can quickly configure the webspace such that uploading to the libvolk.org documentation is possible from the pipeline.
