### ISSUE TITLE
Please tag the version in the CMake script so API changes can be detected

### ISSUE THREAD

**Issue by carlesfernandez** [gnuradio/volk#84]
The interface of volk_32f_index_max_16u have changed as per gnuradio/volk@cb83e1c . This breaks building of projects linking to Volk, so fixes such as https://github.com/gnss-sdr/gnss-sdr/pull/30 won't work if the user has installed Volk through the libvolk1-dev (1.2.2-1) package in Debian and Ubuntu systems, or has built Volk from the 1.2.2 tag.

See https://github.com/gnss-sdr/gnss-sdr/issues/31 for an example.

Adding

```
set(VERSION_INFO_MAINT_VERSION 2git)
```

could help to detect that change and adapt the code adequately, since it is exported through PC_VOLK_VERSION

**Comment by n-west** [comment]
I'm going through the release now. This was a mistake on my part to merge the change in to maint.
