### ISSUE TITLE
cannot convert ‘ unsigned int* ’ to ‘ uint16_t* {aka short unsigned int*} ’ in argument passing

### ISSUE THREAD

**Issue by sgardner340** [gnuradio/volk#90]
I have had this error using the latest Gunradio since 05/26/2016. Looks like Volk was updated and the update conflicts with Gnuradio's gr-dtv component 

Error Log:
/home/hudson/workspace/PyBombs_Build_All_Ubuntu_Matrix/os/Ubuntu_14.04_Desktop_x86_64_VM_R/satisfy_order/deb-src/src/gr-wimax/lib/phy/phy_estimate_fine_offsets_shmidl_and_cox.cc: In function ‘ bool phy_estimate_fine_offsets_shmidl_and_cox(unsigned int, unsigned int, unsigned int, float, const gr_complex_, unsigned int, unsigned int&, double&, gr_complex_, size_t&) ’:
/home/hudson/workspace/PyBombs_Build_All_Ubuntu_Matrix/os/Ubuntu_14.04_Desktop_x86_64_VM_R/satisfy_order/deb-src/src/gr-wimax/lib/phy/phy_estimate_fine_offsets_shmidl_and_cox.cc: 45: 78: error: cannot convert ‘ unsigned int\* ’ to ‘ uint16_t\* {aka short unsigned int_} ’ in argument passing
volk_32fc_index_max_16u( &M_max, (lv_32fc_t_) &crossvec[0], num_crossvals);
^
make[2]: **\* [lib/CMakeFiles/ofdma.dir/phy/phy_estimate_fine_offsets_shmidl_and_cox.cc.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
make[1]: **\* [lib/CMakeFiles/ofdma.dir/all] Error 2
make: **\* [all] Error 2

**Comment by n-west** [comment]
This was fixed
