### ISSUE TITLE
Cheetah template engine is deprecated

### ISSUE THREAD

**Issue by stwunsch** [gnuradio/volk#95]
#94

**Comment by stwunsch** [comment]
Do you still want to port everything to mako? Was not much work, so here it is!

**Comment by n-west** [comment]
Thanks! this can't be merged in to maint/master quite yet, but I pulled it in to master-mako for when we're ready to change deps.

**Comment by stwunsch** [comment]
Alright! Please note: Mako version needs to be checked vs repository versions of old linux dists (and whether it works with this version). I simply put in the version used by gr-utils/gr_modtool.
