### ISSUE TITLE
test_all fails for volk_32fc_magnitude_32f on ARM (ODROID-XU4)

### ISSUE THREAD

**Issue by ghost** [gnuradio/volk#96]
I have included the full commands and output here:
https://paste.fedoraproject.org/391950/

And I did read this Issue - https://github.com/gnuradio/volk/issues/53 so I know that the below fail is not a show stopper, it just might confuse someone who does not dig as deep into failure messages.

But to save time here are what I think are the few relevant lines:
... snip ...
RUN_VOLK_TESTS: volk_32fc_magnitude_32f(131071,1)
generic completed in 1.112ms
a_generic completed in 1.142ms
neon completed in 0.512ms
neon_fancy_sweet completed in 0.666ms
offset 45 in1: 0.694743 in2: 0.701749 tolerance was: 0.01
**offset 50 in1: 1.12784 in2: 1.13924 tolerance was: 0.01**
offset 53 in1: 0.675194 in2: 0.682 tolerance was: 0.01
**offset 85 in1: 1.18012 in2: 1.19196 tolerance was: 0.01**
offset 165 in1: 0.605393 in2: 0.611502 tolerance was: 0.01
offset 207 in1: 0.779736 in2: 0.787542 tolerance was: 0.01
offset 238 in1: 0.922005 in2: 0.931302 tolerance was: 0.01
offset 248 in1: 0.223862 in2: 0.226108 tolerance was: 0.01
offset 293 in1: 0.947177 in2: 0.956736 tolerance was: 0.01
offset 309 in1: 0.708327 in2: 0.715429 tolerance was: 0.01
volk_32fc_magnitude_32f: fail on arch neon_fancy_sweet
Best aligned arch: neon
Best unaligned arch: neon
Failure on volk_32fc_magnitude_32f
... snip ...

**Comment by n-west** [comment]
Ack. Thanks for the report. I'll adjust tolerances for this test again so they are accurate for NEON
