### ISSUE TITLE
volk_profile -u breaks volk_config?

### ISSUE THREAD

**Issue by bobbib** [gnuradio/volk#98]
After running `volk_profile`, and then `volk_profile -u`,
`~/.volk/volk_config` becomes unusable by apps using libvolk;
e. g., Gqrx even crashes:

> Volk warning: no arch found, returning generic impl
> Volk warning: no arch found, returning generic impl
> Segmentation fault

dmesg:
`[15609.066468] traps: complex_to_flo2[8965] general protection ip:7f7fbf54b930 sp:7f7f911e2078 error:0 in libvolk.so.1.3[7f7fbf492000+14e000]`

Version: VOLK 1.3 (actually, Debian "libvolk1.3" & "libvolk1-bin" amd64 binaries version 1.3-1).

volk_config samples attached.

[volk_config.bad.txt](https://github.com/gnuradio/volk/files/374851/volk_config.bad.txt)
[volk_config.orig.txt](https://github.com/gnuradio/volk/files/374852/volk_config.orig.txt)

**Comment by n-west** [comment]
should be fixed in 0d672945dfca506d4e49e857ce886d2b3dc80e96. thanks for the report
